import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import AutoBreadcrumb from "@/components/auto-breadcrumb";
import { DM_Sans} from "next/font/google"
import "./globals.css";
export const metadata: Metadata = {
  title: "Campus Connect",
  description: "Generated by create next app",
};
const dm_sans  = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  subsets: ["latin"]
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${dm_sans.className} antialiased`} >
      <body>
        <Header />
        <AutoBreadcrumb />
        {children}
        <Footer />
      </body>
    </html>
  );
}