import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { clash_grotesk } from "@/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Campus Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${clash_grotesk.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
